### PR TITLE
Update OldDiscordFont.theme.css

### PR DESCRIPTION
**Pull request by TheRealStew**
no more load error

### CODE REVIEW

**Comment by celunah** [comment]
what does an @import rule have to do with the theme loading or not

**Comment by snappycreeper** [comment]
seems to work for everyone else, may I ask what import does?

**Comment by celunah** [comment]
> seems to work for everyone else, may I ask what import does?

@import is the CSS rule for linking an external stylesheet in your CSS file

considering that this CSS file already has the CSS rules made, and the @import just imports itself again, it either creates duplicate rules, or does simply nothing and is useless

@TheRealStew please don't use @import if you don't know what it does, the load error is on you, it works for everyone else

**Comment by celunah** [comment]
took you a long time @snappycreeper

**Comment by snappycreeper** [comment]
whoops sorry

**Pull request closed without merging**
